import { Navbar } from "@/components";
import LanguageContextProvider from "@/context/LanguageContext";
import ModalContextProvider from "@/context/ModalContext";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import { MobileMenu } from "@/components/ui/MobileMenu";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <LanguageContextProvider>
          <ModalContextProvider>
        <Navbar />
        <MobileMenu/>
          {children}
        <ToastContainer style={{ fontSize: "1rem" }} />
        </ModalContextProvider>
        </LanguageContextProvider>
      </body>
    </html>
  );
}
